import type { Locale } from "@/lib/i18n";

const ar = {
  viewDetails: "عرض التفاصيل",
  bookTitle: "طلب حجز جولة",
  touristDetails: "تفاصيل الطلب",
  dateLabel: "تاريخ الجولة",
  startTimeLabel: "وقت البدء",
  durationLabel: "المدة (بالساعات)",
  participantsLabel: "عدد المشاركين",
  meetingPointLabel: "نقطة اللقاء المفضلة",
  meetingPointPlaceholder: "مثال: مقهى كذا، أو الفندق...",
  summaryTitle: "ملخص الحجز",
  guideName: "المرشد:",
  hourlyRate: "سعر الساعة:",
  totalPrice: "السعر الإجمالي:",
  submitRequest: "إرسال الطلب للمرشد",
  successMessage: "تم إرسال طلبك بنجاح! بانتظار موافقة المرشد.",
  errorMessage: "حدث خطأ أثناء إرسال الطلب. يرجى المحاولة مرة أخرى.",
  invalidDate: "يرجى اختيار تاريخ ووقت صحيحين في المستقبل.",
  loginRequired: "يجب تسجيل الدخول كـ (سائح) لتقديم طلب حجز.",
  backToGuide: "العودة لملف المرشد",
  myBookings: "حجوزاتي",
  noBookings: "لا توجد حجوزات لعرضها.",
  touristLabel: "السائح:",
  guideLabel: "المرشد:",
  hours: "ساعات",
  acceptBooking: "قبول",
  declineBooking: "رفض",
  cancelBooking: "إلغاء",
  payNow: "دفع الآن",
  paymentSoon: "بوابة الدفع قادمة في المرحلة القادمة!",
  confirmAction: "هل أنت متأكد من هذا الإجراء؟",
  status: {
    pending: "قيد الانتظار",
    awaiting_payment: "بانتظار الدفع",
    confirmed: "مؤكد",
    in_progress: "قيد التنفيذ",
    completed: "مكتمل",
    cancelled: "ملغي",
    declined: "مرفوض",
    expired: "منتهي"
  },
  earningsTitle: "الأرباح والمستحقات",
  totalEarnings: "إجمالي الأرباح",
  pendingEarnings: "أرباح معلقة",
  availableEarnings: "أرباح متاحة للسحب",
  platformFee: "رسوم المنصة",
  netAmount: "الصافي",
  bookingReference: "رقم الحجز",
  
  operations: {
    startTour: "بدء الجولة",
    endTour: "إنهاء الجولة",
    enterOtp: "أدخل رمز التأكيد",
    touristOtpNote: "أعط هذا الرمز للمرشد لبدء الجولة:",
    tourStarted: "بدأت الجولة بنجاح",
    tourEnded: "انتهت الجولة",
    invalidOtp: "الرمز غير صحيح",
    chat: "المحادثة",
    typeMessage: "اكتب رسالة...",
    send: "إرسال"
  },
  geolocation_not_supported: "المتصفح لا يدعم تحديد الموقع",
  broadcasting_location: "يتم بث الموقع الجغرافي...",
  share_live_location: "بث الموقع الجغرافي الحي",
  tourist_can_see_location: "السائح يستطيع رؤية موقعك الآن",
  share_location_desc: "ساعد السائح في الوصول إليك بسهولة",
  stop: "إيقاف",
  start: "بدء",
  waiting_for_location: "في انتظار بث المرشد لموقعه الجغرافي...",
  guide_is_broadcasting: "المرشد يقوم ببث موقعه الجغرافي",
  open_in_maps: "فتح في الخرائط",
  review_submitted: "تم تقديم التقييم",
  complaint_submitted: "تم تقديم الشكوى",
  please_select_rating: "يرجى اختيار تقييم",
  review_success: "شكراً لتقييمك!",
  please_enter_reason: "يرجى كتابة سبب الشكوى",
  complaint_success: "تم إرسال شكواك، سنقوم بمراجعتها قريباً.",
  leave_review: "تقييم المرشد",
  report_issue: "الإبلاغ عن مشكلة",
  cancel: "إلغاء",
  review_placeholder: "كيف كانت الجولة؟ (اختياري)",
  submit: "إرسال",
  complaint_reason_label: "ما المشكلة التي واجهتها؟",
  complaint_placeholder: "يرجى وصف المشكلة...",
  submit_complaint: "إرسال الشكوى"
};

const en = {
  viewDetails: "View details",
  bookTitle: "Request a Tour Booking",
  touristDetails: "Booking Details",
  dateLabel: "Tour Date",
  startTimeLabel: "Start Time",
  durationLabel: "Duration (Hours)",
  participantsLabel: "Number of Participants",
  meetingPointLabel: "Preferred Meeting Point",
  meetingPointPlaceholder: "e.g., A specific cafe, or your hotel...",
  summaryTitle: "Booking Summary",
  guideName: "Guide:",
  hourlyRate: "Hourly Rate:",
  totalPrice: "Total Price:",
  submitRequest: "Submit Request to Guide",
  successMessage: "Your request has been submitted successfully! Waiting for the guide's approval.",
  errorMessage: "An error occurred while submitting the request. Please try again.",
  invalidDate: "Please select a valid future date and time.",
  loginRequired: "You must log in as a tourist to submit a booking request.",
  backToGuide: "Back to Guide Profile",
  myBookings: "My Bookings",
  noBookings: "No bookings to display.",
  touristLabel: "Tourist:",
  guideLabel: "Guide:",
  hours: "hours",
  acceptBooking: "Accept",
  declineBooking: "Decline",
  cancelBooking: "Cancel",
  payNow: "Pay Now",
  paymentSoon: "Payment gateway coming in the next phase!",
  confirmAction: "Are you sure you want to perform this action?",
  status: {
    pending: "Pending",
    awaiting_payment: "Awaiting Payment",
    confirmed: "Confirmed",
    in_progress: "In Progress",
    completed: "Completed",
    cancelled: "Cancelled",
    declined: "Declined",
    expired: "Expired"
  },
  earningsTitle: "Earnings & Payouts",
  totalEarnings: "Total Earnings",
  pendingEarnings: "Pending Earnings",
  availableEarnings: "Available for Payout",
  platformFee: "Platform Fee",
  netAmount: "Net Amount",
  bookingReference: "Booking Ref",

  operations: {
    startTour: "Start Tour",
    endTour: "End Tour",
    enterOtp: "Enter Confirmation Code",
    touristOtpNote: "Give this code to the guide to start the tour:",
    tourStarted: "Tour started successfully",
    tourEnded: "Tour ended",
    invalidOtp: "Invalid code",
    chat: "Chat",
    typeMessage: "Type a message...",
    send: "Send"
  },
  geolocation_not_supported: "Geolocation is not supported by your browser",
  broadcasting_location: "Broadcasting Location...",
  share_live_location: "Share Live Location",
  tourist_can_see_location: "The tourist can see your live location",
  share_location_desc: "Help the tourist find you easily",
  stop: "Stop",
  start: "Start",
  waiting_for_location: "Waiting for guide's live location...",
  guide_is_broadcasting: "Guide is broadcasting location",
  open_in_maps: "Open in Maps",
  review_submitted: "Review Submitted",
  complaint_submitted: "Complaint Submitted",
  please_select_rating: "Please select a rating",
  review_success: "Thank you for your feedback!",
  please_enter_reason: "Please enter a reason",
  complaint_success: "Complaint submitted. We will review it shortly.",
  leave_review: "Leave a Review",
  report_issue: "Report an Issue",
  cancel: "Cancel",
  review_placeholder: "How was your tour? (Optional)",
  submit: "Submit",
  complaint_reason_label: "What went wrong?",
  complaint_placeholder: "Please describe the issue...",
  submit_complaint: "Submit Complaint"
};

export function bookingsMessages(locale: Locale) {
  return locale === "ar" ? ar : en;
}
